// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oewwumdsxvzbysqqfdox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ld3d1bWRzeHZ6YnlzcXFmZG94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDYwMDYsImV4cCI6MjA3MjgyMjAwNn0.czOvYxKJuLX7bSfZCmCHt7lqryWMJCtWBB6ZJDuXp1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});